# This file was generated by GoReleaser. DO NOT EDIT.
class Fakelish < Formula
  desc "Fake English word generator"
  homepage "https://github.com/nwtgck/go-fakelish"
  version "0.1.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nwtgck/go-fakelish-release-test/releases/download/v0.1.8/fakelish-0.1.8-darwin-amd64.tar.gz"
    sha256 "7307b3595a7d2c440228259d0cc3ebee6b4f3afda003c1efbafcf68fb7364724"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/nwtgck/go-fakelish-release-test/releases/download/v0.1.8/fakelish-0.1.8-linux-amd64.tar.gz"
      sha256 "150d4d0afdc46c934e51fdc20d6e7271bbc0d182d5a9c6a0b639068c757f49c6"
    end
  end

  def install
    bin.install "fakelish"
  end
end
