# This file was generated by GoReleaser. DO NOT EDIT.
class Fakelish < Formula
  desc "Fake English word generator"
  homepage "https://github.com/nwtgck/go-fakelish"
  version "0.1.12"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/nwtgck/go-fakelish-release-test/releases/download/v0.1.12/fakelish-0.1.12-darwin-amd64.tar.gz"
    sha256 "76dc1af8e65a07546b808b36c06fafafc6131772d8660992ff051a13170b9fe3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/nwtgck/go-fakelish-release-test/releases/download/v0.1.12/fakelish-0.1.12-linux-amd64.tar.gz"
    sha256 "573a3656c58bd420909e6a42882d89d90fc2b3469a4a3e838a0902476eebb17f"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/go-fakelish-release-test/releases/download/v0.1.12/fakelish-0.1.12-linux-armv6.tar.gz"
    sha256 "2cbfbda86014fdc23263e553f5f6ba56b881e3c389d06bce85c9597933acbe79"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/nwtgck/go-fakelish-release-test/releases/download/v0.1.12/fakelish-0.1.12-linux-arm64.tar.gz"
    sha256 "a59fe18bd10fbf2569a7c3d7855a20d04a2ba77889fe290dfad9c99972300d64"
  end

  def install
    bin.install "fakelish"
  end
end
